### ISSUE TITLE
Markdown elements not displaying properly

### ISSUE THREAD

**Issue by ArnoldTingSu** [nuxt-themes/alpine#173]
![image](https://github.com/nuxt-themes/alpine/assets/26914510/af6b6720-d079-4347-a62a-87e88dfd2656)

VS Code set to Markdown, yet formatting updates and causes markdown to break

**Comment by leafleaf90** [comment]
@ArnoldTingSu 
Are you using Prettier to format? If so, you need to add .md to your prettierignore file.

Create a file in the root named ".prettierignore" and just add this one line:
*.md

The reason is that Prettier format to standard markdown, but this is MDC.

Related to this issue on Nuxt Content repo:
https://github.com/nuxt/content/issues/1709

**Comment by ArnoldTingSu** [comment]
Thank you. The setting worked
